return function(cp, colors)
    return {
        BufferLineFill                  = { bg = colors.bg_dark },
        BufferLineBackground            = { fg = cp.cool_dark_grey, bg = colors.bg_dark },
        BufferLineBufferSelected        = { fg = cp.black, bg = colors.bg, bold = true },
        BufferLineBufferVisible         = { fg = cp.cool_dark_grey, bg = colors.bg_dark },
        BufferLineTabSelected           = { fg = cp.black, bg = cp.selection, bold = true },
        BufferLineIndicatorSelected     = { fg = cp.denim, bg = colors.bg },
        BufferLineModified              = { fg = cp.orange, bg = colors.bg_dark },
        BufferLineModifiedVisible       = { fg = cp.orange, bg = colors.bg_dark },
        BufferLineModifiedSelected      = { fg = cp.orange, bg = colors.bg, bold = true },
        BufferLineError                 = { fg = cp.auburn, bg = colors.bg_dark },
        BufferLineErrorSelected         = { fg = cp.auburn, bg = colors.bg, bold = true },
        BufferLineWarning               = { fg = cp.orange, bg = colors.bg_dark },
        BufferLineWarningSelected       = { fg = cp.orange, bg = colors.bg, bold = true },
        BufferLineInfo                  = { fg = cp.sky, bg = colors.bg_dark },
        BufferLineInfoSelected          = { fg = cp.sky, bg = colors.bg },
        BufferLineHint                  = { fg = cp.lake, bg = colors.bg_dark },
        BufferLineHintSelected          = { fg = cp.lake, bg = colors.bg },
        BufferLineDuplicate             = { fg = cp.cool_dark_grey, bg = colors.bg_dark },
        BufferLineDuplicateSelected     = { fg = cp.black, bg = colors.bg, bold = true },
        BufferLineSeparator             = { fg = cp.cool_dark_grey, bg = colors.bg_dark },
        BufferLineSeparatorSelected     = { fg = cp.denim, bg = colors.bg },
        BufferLineSeparatorVisible      = { fg = cp.cool_medium_grey, bg = colors.bg_dark },
        BufferLineCloseButton           = { fg = cp.cool_dark_grey, bg = colors.bg_dark },
        BufferLineCloseButtonSelected   = { fg = cp.black, bg = colors.bg },
        BufferLineCloseButtonVisible    = { fg = cp.cool_dark_grey, bg = colors.bg_dark },
        BufferLineTab                   = { fg = cp.cool_dark_grey, bg = colors.bg_dark },
        BufferLineTabClose              = { fg = cp.cool_dark_grey, bg = colors.bg_dark },
        BufferLineOffsetSeparator       = { fg = cp.cool_dark_grey, bg = colors.bg },
        BufferLinePick                  = { fg = cp.cobalt, bg = colors.bg_dark, bold = true },
        BufferLinePickSelected          = { fg = cp.cobalt, bg = colors.bg, bold = true },
        BufferLineGroupBackground       = { bg = colors.bg_dark },
        BufferLineGroupError            = { fg = cp.auburn, bg = colors.bg_dark },
        BufferLineGroupWarning          = { fg = cp.orange, bg = colors.bg_dark },
        BufferLineGroupInfo             = { fg = cp.sky, bg = colors.bg_dark },
        BufferLineGroupHint             = { fg = cp.lake, bg = colors.bg_dark },
    }
end
