return function(cp, colors)
    return {
        SnacksNormal       = { fg = cp.black, bg = colors.float_bg },
        SnacksBorder       = { fg = cp.cool_medium_grey, bg = colors.float_bg },
        SnacksTitle        = { fg = cp.denim, bg = colors.float_bg, bold = true },
        SnacksBackdrop     = { fg = cp.black, bg = colors.float_bg },
        SnacksPicker       = { link = 'SnacksNormal' },
        SnacksPickerBorder = { link = 'SnacksBorder' },
        SnacksPickerTitle  = { fg = cp.denim, bg = colors.float_bg, bold = true },
        SnacksInput        = { fg = cp.black, bg = colors.float_bg },
        SnacksInputBorder  = { fg = cp.denim, bg = colors.float_bg },
        SnacksSelector     = { bg = cp.selection },
        SnacksMatching     = { fg = cp.cobalt, bold = true },
        SnacksDashboard    = { fg = cp.black, bg = colors.bg },
        SnacksDashboardDesc = { fg = cp.cool_dark_grey },
        SnacksDashboardFile = { fg = cp.denim },
        SnacksDashboardHeader = { fg = cp.denim, bold = true },
        SnacksDashboardIcon  = { fg = cp.aqua },
        SnacksDashboardKey   = { fg = cp.aqua, bold = true },
        SnacksDashboardTitle = { fg = cp.cobalt, bold = true },
        SnacksIndicator = { fg = cp.grass },
        SnacksNotifier  = { link = 'NormalFloat' },
        SnacksNotifierBorder = { link = 'FloatBorder' },
        SnacksNotifierTitle  = { fg = cp.denim, bold = true },
        SnacksNotifierIcon   = { fg = cp.cool_dark_grey },
        SnacksNotifierError  = { fg = cp.auburn },
        SnacksNotifierWarn   = { fg = cp.orange },
        SnacksNotifierInfo   = { fg = cp.sky },
        SnacksNotifierDebug  = { fg = cp.cool_dark_grey },
        SnacksNotifierTrace  = { fg = cp.cool_dark_grey },
        SnacksIndent         = { fg = cp.cool_light_grey },
        SnacksIndentScope    = { fg = cp.denim },
    }
end
